"""Helper script to launch the distortion step from an IDE.

Edit the path constants below so they point to your dataset, then run the
module from your IDE or a terminal (``python scripts/run_distord_command.py``).
The script simply forwards the call to ``python -m src.distord`` using the same
interpreter that executed the file, which guarantees the package imports resolve
correctly as long as you start it from inside the repository.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent

    # distord.py expects the aligned segmentation generated by align.py so the
    # EBSD and segment share the exact same dimensions.
# =============================================================================
#     seg_ref_path = repo_root / "data/AM718/segment.align/segment.align.0.png"
#     ebsd_ref_path = repo_root / "data/AM718/ebsd/AM718_ebsd.jpg"
#     # Set to ``None`` if you do not have ANG metadata and only need the PNG outputs.
#     ang_ref_path = repo_root / "data/AM718/ang/AM718.ang"
#     out_dir = repo_root / "data/AM718/out"
#     # The distortion step does not take the JSON configuration used by align.py,
#     # but keeping the path documented here makes it easier to see which project
#     # we are working with when editing the script.
#     config_path = repo_root / "conf/AM718.align.conf"
# =============================================================================
    reference_mode = "semcl"  # Choose between "semcl" or "ebsd" as the reference image
    swap_segment_and_reference = False  # Set to True if you want to flip which image is passed as the segment
    enable_auto_crop = False  # Set to True to center-crop a larger EBSD frame
    truncate_overlap = True  # Set to False to keep the full images even if they differ in size

    # Paths for the two possible reference images you may want to test with.
    semcl_reference_path = repo_root / "data/RV/binary_semcl_halfstone_floyd_cropped_compress.png"
    ebsd_reference_path = repo_root / "data/RV/binary_ebsd_halfstone_floyd_maskout_black_compress.png"

    reference_paths = {
        "semcl": semcl_reference_path,
        "ebsd": ebsd_reference_path,
    }

    try:
        selected_reference = reference_paths[reference_mode]
    except KeyError as exc:
        raise SystemExit(f"Unsupported reference_mode '{reference_mode}'. Use one of: {', '.join(reference_paths)}") from exc

    seg_ref_path = repo_root / "data/RV/segment.align/segment.align.0.png"
    ebsd_ref_path = selected_reference

    if swap_segment_and_reference:
        seg_ref_path, ebsd_ref_path = ebsd_ref_path, seg_ref_path

    # Set to ``None`` if you do not have ANG metadata and only need the PNG outputs.
    ang_ref_path = None
    out_dir = repo_root / "data/RV/out"
    # The distortion step does not take the JSON configuration used by align.py,
    # but keeping the path documented here makes it easier to see which project
    # we are working with when editing the script.
    config_path = repo_root / "conf/RV.align.conf"
    xp_id = 0
    mesh_step = 105
    mesh_std = 5
    num_sampling = 100
    polynom = 3

    out_dir.mkdir(parents=True, exist_ok=True)

    command = [
        sys.executable,
        "-m",
        "src.distord",
        "-seg_ref_path",
        str(seg_ref_path),
        "-ebsd_ref_path",
        str(ebsd_ref_path),
        "-out_dir",
        str(out_dir),
        "-id_xp",
        str(xp_id),
        "-mesh_step",
        str(mesh_step),
        "-mesh_std",
        str(mesh_std),
        "-num_sampling",
        str(num_sampling),
        "-polynom",
        str(polynom),
    ]

    if enable_auto_crop:
        command.append("-auto_crop")

    if truncate_overlap:
        command.append("-truncate_overlap")

    if ang_ref_path is not None:
        command.extend(["-ang_ref_path", str(ang_ref_path)])

    print(f"Configuration template: {config_path}")
    print(
        "Reference mode: {ref_mode} | swap_segment_and_reference={swap} | auto_crop={auto} | truncate_overlap={truncate}".format(
            ref_mode=reference_mode,
            swap=swap_segment_and_reference,
            auto=enable_auto_crop,
            truncate=truncate_overlap,
        )
    )
    print("Running:", " ".join(command))

    result = subprocess.run(
        command,
        check=False,
        capture_output=True,
        text=True,
    )

    if result.stdout:
        print(result.stdout)

    if result.stderr:
        print(result.stderr, file=sys.stderr)

    if result.returncode != 0:
        raise SystemExit(
            "distord failed. Review the error output above (missing Python "
            "packages such as numpy/opencv is the most common cause)."
        )


if __name__ == "__main__":
    main()
